# Generated by Django 3.2 on 2021-04-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_message',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_subject',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
