# Generated by Django 3.2 on 2021-04-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='user')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=122, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=122, null=True)),
            ],
        ),
    ]
